"""Imitation-learning dataset preparation utilities."""

from gd_imitation.baseline import (
    BaselineTrainingConfig,
    ImitationBaselineError,
    binary_classification_metrics,
    load_or_create_split,
    predict_baseline_from_checkpoint,
    train_baseline_from_dataset_dir,
    train_imitation_baseline,
)
from gd_imitation.dataset import (
    DatasetConfig,
    DatasetPrepError,
    DatasetSplit,
    ImitationSample,
    build_imitation_samples,
    load_imitation_samples,
    load_samples_jsonl,
    split_imitation_samples,
)
from gd_imitation.decoder import (
    DecoderConfig,
    EventCandidate,
    EventDecoderError,
    PredictionPoint,
    decode_predictions,
    event_level_metrics,
    load_prediction_jsonl,
    select_event_candidates,
)
from gd_imitation.image_dataset import (
    GrayscaleFrame,
    ImageDatasetConfig,
    ImageDatasetError,
    ImageInputSample,
    load_image_dataset,
    load_image_input_sample,
    load_prepared_image_dataset,
    read_bmp_grayscale,
    read_bmp_grayscale_resized,
    resize_grayscale_frame,
)

__all__ = [
    "BaselineTrainingConfig",
    "DatasetConfig",
    "DatasetPrepError",
    "DatasetSplit",
    "DecoderConfig",
    "EventCandidate",
    "EventDecoderError",
    "ImitationSample",
    "GrayscaleFrame",
    "ImitationBaselineError",
    "ImageDatasetConfig",
    "ImageDatasetError",
    "ImageInputSample",
    "PredictionPoint",
    "binary_classification_metrics",
    "build_imitation_samples",
    "decode_predictions",
    "event_level_metrics",
    "load_image_dataset",
    "load_image_input_sample",
    "load_imitation_samples",
    "load_or_create_split",
    "load_prediction_jsonl",
    "load_prepared_image_dataset",
    "load_samples_jsonl",
    "predict_baseline_from_checkpoint",
    "read_bmp_grayscale",
    "read_bmp_grayscale_resized",
    "resize_grayscale_frame",
    "select_event_candidates",
    "split_imitation_samples",
    "train_baseline_from_dataset_dir",
    "train_imitation_baseline",
]
