"""RL-practice scaffolding for level-specific Geometry Dash agents."""

from gd_rl.actions import ActionKind, IntendedAction, actions_to_events
from gd_rl.geode_executor import GeodeExecutorConfig, GeodePracticeExecutor
from gd_rl.live_env import (
    LiveGeodeClientLike,
    LivePracticeEnv,
    LivePracticeEnvConfig,
    LivePracticeObservation,
    LiveStepResult,
)
from gd_rl.live_learner import (
    ACTION_KINDS,
    LiveLearnerError,
    LiveObservationEncoderConfig,
    NeuralActionDecision,
    NeuralPolicyConfig,
    ReinforceAttemptSummary,
    ReinforceConfig,
    ReinforceTrainingSummary,
    TinyLivePolicyNetwork,
    encode_live_observation,
    live_observation_feature_dim,
    run_reinforce_attempt,
    run_reinforce_training,
)
from gd_rl.policy import (
    NoInputPolicy,
    PracticeContext,
    PracticePolicy,
    RandomEventPolicy,
    ScriptedEventPolicy,
)
from gd_rl.results import AttemptResult, PracticeRunSummary
from gd_rl.rewards import (
    RewardBreakdown,
    RewardConfig,
    TraceOutcome,
    compute_reward,
    summarize_trace_outcome,
)
from gd_rl.runner import PracticeAttemptExecutor, PracticeRunConfig, PracticeRunner
from gd_rl.timing_search import (
    CandidateEvaluation,
    GenerationResult,
    TimingCandidate,
    TimingEventWindow,
    TimingSearchConfig,
    TimingSearchResult,
    load_timing_windows_json,
    run_timing_search,
    sample_candidate,
    update_windows_from_elites,
)

__all__ = [
    "ActionKind",
    "ACTION_KINDS",
    "AttemptResult",
    "CandidateEvaluation",
    "GeodeExecutorConfig",
    "GeodePracticeExecutor",
    "GenerationResult",
    "IntendedAction",
    "LiveGeodeClientLike",
    "LiveLearnerError",
    "LiveObservationEncoderConfig",
    "LivePracticeEnv",
    "LivePracticeEnvConfig",
    "LivePracticeObservation",
    "LiveStepResult",
    "NeuralActionDecision",
    "NeuralPolicyConfig",
    "NoInputPolicy",
    "PracticeAttemptExecutor",
    "PracticeContext",
    "PracticePolicy",
    "PracticeRunConfig",
    "PracticeRunSummary",
    "PracticeRunner",
    "RandomEventPolicy",
    "ReinforceAttemptSummary",
    "ReinforceConfig",
    "ReinforceTrainingSummary",
    "RewardBreakdown",
    "RewardConfig",
    "ScriptedEventPolicy",
    "TimingCandidate",
    "TimingEventWindow",
    "TimingSearchConfig",
    "TimingSearchResult",
    "TraceOutcome",
    "TinyLivePolicyNetwork",
    "actions_to_events",
    "compute_reward",
    "encode_live_observation",
    "live_observation_feature_dim",
    "load_timing_windows_json",
    "run_reinforce_attempt",
    "run_reinforce_training",
    "run_timing_search",
    "sample_candidate",
    "summarize_trace_outcome",
    "update_windows_from_elites",
]
